### ISSUE TITLE
Program crashes when window is moved or resized

### ISSUE THREAD

**Issue by blueridanus** [msiglreith/gfx_ocean#1]
```
thread 'main' panicked at 'Unable to acquire a swapchain image: ErrorOutOfDateKhr', src/libcore/result.rs:906:4

stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
             at /build/rust/src/rustc-1.21.0-src/src/libcore/macros.rs:41
  10: <core::result::Result<T, E>>::expect
             at /build/rust/src/rustc-1.21.0-src/src/libcore/result.rs:799
  11: <gfx_backend_vulkan::window::Swapchain as gfx_hal::window::Swapchain<gfx_backend_vulkan::Backend>>::acquire_frame
             at /root/.cargo/git/checkouts/gfx-a2211557a9643c54/23aeb64/src/backend/vulkan/src/window.rs:342
  12: ocean::main
             at src/main.rs:875
  13: __rust_maybe_catch_panic
  14: std::panicking::try
  15: std::rt::lang_start
  16: main
  17: __libc_start_main
  18: _start

```

**Comment by hlavaatch** [comment]
Swap chain needs to be recreated when window is resized
